// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClassLibrary1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ClassLibrary1.Models.Configurations
{
    public partial class AttendeeConfiguration : IEntityTypeConfiguration<Attendee>
    {
        public void Configure(EntityTypeBuilder<Attendee> entity)
        {
            entity.HasKey(e => new { e.GatheringId, e.MemberId });

            entity.HasIndex(e => e.MemberId, "IX_Attendees_MemberId");

            entity.HasOne(d => d.Gathering).WithMany(p => p.Attendees).HasForeignKey(d => d.GatheringId);

            entity.HasOne(d => d.Member).WithMany(p => p.Attendees)
            .HasForeignKey(d => d.MemberId)
            .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Attendee> entity);
    }
}
