// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClassLibrary1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ClassLibrary1.Models.Configurations
{
    public partial class GatheringConfiguration : IEntityTypeConfiguration<Gathering>
    {
        public void Configure(EntityTypeBuilder<Gathering> entity)
        {
            entity.HasIndex(e => e.CreatorId, "IX_Gatherings_CreatorId");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Creator).WithMany(p => p.Gatherings).HasForeignKey(d => d.CreatorId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Gathering> entity);
    }
}
