// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClassLibrary1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ClassLibrary1.Models.Configurations
{
    public partial class OutboxMessageConsumerConfiguration : IEntityTypeConfiguration<OutboxMessageConsumer>
    {
        public void Configure(EntityTypeBuilder<OutboxMessageConsumer> entity)
        {
            entity.HasKey(e => new { e.Id, e.Name });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OutboxMessageConsumer> entity);
    }
}
